[global]
log_level = 'debug'

[rest]
enabled = true
host = '127.0.0.1'
port = 4010

[telemetry]
enabled = true
host = '127.0.0.1'
port = 4011

[[chains]]
id = 'bbn'
rpc_addr = 'https://rpc-euphrates.devnet.babylonchain.io:443'
grpc_addr = 'https://rpc-euphrates.devnet.babylonchain.io:443'
websocket_addr = 'https://lcd-euphrates.devnet.babylonchain.io:443'
rpc_timeout = '10s'
account_prefix = 'bbn'
key_name = 'bbn'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.001, denom = 'ubbn' }
gas_adjustment = 0.1
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'mars'
rpc_addr = 'http://0.0.0.0:26657'
grpc_addr = 'http://0.0.0.0:1317'
websocket_addr = 'ws://localhost:26559/websocket'
rpc_timeout = '10s'
account_prefix = 'mars'
key_name = 'greenman'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.001, denom = 'ubbn' }
gas_adjustment = 0.1
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
